products/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('projects','ProjectsController');

products/app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable =['id','title','description','created_at','updated_at'];

    protected $table="projects";

    public function tasks()
    {
        return $this->hasMany(Task::class,'project_id','id');
    }
}

products/app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['id','project_id','title','description','status'];
    protected $table="tasks";

    public function project()
    {
        return $this->belongsTo(Project::class,'project_id','id');
    }
}

products/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

products/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

products/app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use App\Task;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::all();

        return view('projects.index',compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $this->validateCreate($request->all());
            // dd($request->all());    
        if(!$validate->fails()){
            $project = Project::create($request->except('tasks'));
            
            // Create Project tasks
            foreach ($request->tasks as $task) {
                Task::create([
                    'project_id' => $project->id,
                    'title' => $task['title'],
                    'status' => $task['status'] ? $task['status'] : null,
                ]);
            }
        }

        return redirect()->route('projects.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $project = Project::find($id);

        return view('projects.show',compact('project'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = Project::where('id',$id)->with('tasks')->first();

        return view('projects.update',compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data= $request->all();
        $data['id'] = $id;
        $validate = $this->validateUpdate($data);

        if(!$validate->fails()){
            $project =Project::find($id);
             $project->update($request->except(['tasks','_token','_method']));
            
            // Create Project tasks
            Task::where('project_id',$id)->delete();
            foreach ($request->tasks as $task) {
                Task::create([
                    'project_id' => $project->id,
                    'title' => $task['title'],
                    'status' => $task['status'] ? $task['status'] : null,
                ]);
            }
        }
        return redirect()->route('projects.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Project::where('id',$id)->delete();

        return redirect()->route('projects.index');
    }

    public function validateCreate($data)
    {
        return Validator::make($data, [
            'title' => 'required|string|max:191',
            'description' => 'nullable|string|max:6657',
            'tasks' => 'required|array',
            'tasks.*.title' => 'required|string|max:191',
            'tasks.*.status' => ['required',Rule::in(['done','not_done'])],
            'tasks.*.description' => 'nullable|string|max:6657',
        ]);
    }

    public function validateUpdate($data)
    {
        return Validator::make($data, [
            'id' => 'required|exists:projects,id',
            'title' => 'required|string|max:191',
            'description' => 'nullable|string|max:6657',
            'tasks' => 'required|array',
            'tasks.*.title' => 'required|string|max:191',
            'tasks.*.status' => ['required',Rule::in(['done','not_done'])],
            'tasks.*.description' => 'nullable|string|max:6657',
        ]);
    }
}

products/resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projects</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">

</head>
<body>

@yield('content')

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="{{asset('js/custom.js')}}"></script>
<script src="{{asset('js/repeater.js')}}"></script>

</body>
</html>

products/resources/views/projects/create.blade.php
@extends('layouts.main')

@section('content')
    <form action="{{route('projects.store')}}" method="post">
        {{ csrf_field() }}
        <div class="row">
            <div class="form-group col-6">
                <label for="title">Project title</label>
                <input type="text" class="form-control" name="title">
            </div>
            <div class="form-group col-6">
                <label for="description">Project description</label>
                <input type="text" id="description" class="form-control" name="description">
            </div>
        </div>
        <br>
        <hr>
        <br>
        <div class="row repeater">
            <div data-repeater-list="tasks">
                <div data-repeater-item>
                    <div class="row">
                        <div class="form-group col-6">
                            <label for="title">Task title</label>
                            <input type="text" class="form-control" name="title">
                        </div>
                        {{-- <div class="form-group col-6">
                            <label for="description">Task description</label>
                            <input type="text" id="description" class="form-control" name="description">
                        </div> --}}
                        <div class="form-group col-6">
                            <label for="description">Task Status</label>
                            <select name="status" id="">
                                <option value="done">Done</option>
                                <option value="not_done">Not Done</option>
                            </select>
                        </div>
                     <input data-repeater-delete type="button" value="Delete Task" class="col-3 mt-3"/>
                    </div>

                </div>
              </div>
              <input data-repeater-create type="button" value="Add Task" class="mt-3 col-3" />
        </div>

        <input type="submit" value="Submit">
    </form>
@endsection

products/resources/views/projects/index.blade.php
 @extends('layouts.main')

 @section('content')
    <a href="{{route('projects.create')}}">Create Project</a>

    <table id="project_table">
        <thead>
            <th>id</th>
            <th>title</th>
            <th>done percentage</th>
            <th>actions</th>
        </thead>

        <tbody>
            @foreach($projects as $project)
            <tr>
              <td>{{$project->id}}</td>
              <td>{{$project->title}}</td>  
              @php
                $done_tasks = $project->tasks()->where('status','done')->count();
              @endphp
              <td>{{ $done_tasks ? ($done_tasks / $project->tasks->count()) : 0}}</td>
              <td>
              <a href="{{route('projects.edit',['id'=>$project->id])}}">Update Project</a>

              <form action="{{route('projects.destroy',['id'=>$project->id])}}" method="post">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="delete">
                <input type="submit" value="Delete Project ">
              </form>

              </td>  
            </tr>
            @endforeach
        </tbody>
    </table>
@endsection

products/resources/views/projects/update.blade.php
@extends('layouts.main')

@section('content')
    <form action="{{route('projects.update',['id'=>$project->id])}}" method="post">
        {{ csrf_field() }}
        <div class="row">
            <input type="hidden" name="_method" value="put">
            <div class="form-group col-6">
                <label for="title">Project title</label>
                <input type="text" class="form-control" value="{{$project->title}}"  name="title">
            </div>
            <div class="form-group col-6">
                <label for="description">Project description</label>
                <input type="text" id="description" value="{{$project->description}}" class="form-control" name="description">
            </div>
        </div>
        <br>
        <hr>
        <br>
        <div class="row repeater">
            <div data-repeater-list="tasks">
                @if (count($project->tasks))
                @foreach ($project->tasks as $task)
                <div data-repeater-item>
                    <div class="row">
                        <div class="form-group col-6">
                            <label for="title">Task title</label>
                            <input type="text" class="form-control" value="{{$task->title}}" name="title">
                        </div>
                        {{-- <div class="form-group col-6">
                            <label for="description">Task description</label>
                            <input type="text" id="description"  class="form-control" name="description">
                        </div> --}}
                        <div class="form-group col-6">
                            <label for="description">Task Status</label>
                            <select name="status" id="">
                                <option value="done" @if($task->status == 'done') selected @endif>Done</option>
                                <option value="not_done"  @if($task->status == 'not_done') selected @endif>Not Done</option>
                            </select>
                        </div>
                     <input data-repeater-delete type="button" value="Delete Task" class="col-3 mt-3"/>
                    </div>

                </div>
                @endforeach
                @else
                <div data-repeater-item>
                    <div class="row">
                        <div class="form-group col-6">
                            <label for="title">Task title</label>
                            <input type="text" class="form-control" name="title">
                        </div>
                        <div class="form-group col-6">
                            <label for="description">Task description</label>
                            <input type="text" id="description" class="form-control" name="description">
                        </div>
                        <div class="form-group col-6">
                            <label for="description">Task Status</label>
                            <select name="status" id="">
                                <option value="done">Done</option>
                                <option value="not_done">Not Done</option>
                            </select>
                        </div>
                     <input data-repeater-delete type="button" value="Delete Task" class="col-3 mt-3"/>
                    </div>

                </div>
                @endif


              </div>
              <input data-repeater-create type="button" value="Add Task" class="mt-3 col-3" />
        </div>

        <input type="submit" value="Submit">
    </form>
@endsection